#!/bin/bash

usage()
{
    echo "\n USAGE: ./${0##*/} [AGENT_FQN] \n"
    echo "\t AGENT_FQN : Agent fully qualified name (e.g. io.sarl.demos.basic.HelloAgent)"
    exit
}


[[ $# -lt 1 ]] && usage


MVN=`which mvn`
LOG_LEVEL="-Djava.util.logging.config.file=logging.properties"

JANUS_BOOT="exec:java -Dexec.mainClass=io.janusproject.Boot $LOG_LEVEL"

AGENT="-Dexec.args=$*"

RUN_CMD="$MVN -q $JANUS_BOOT $AGENT"

echo "--------------------------------------------------"
echo "- Running Janus Platfrom"
echo "- AGENT: $*"
echo "- RUN CMD: $RUN_CMD"
echo "--------------------------------------------------"

$RUN_CMD

